"""initial setup

Revision ID: 0558e74947c6
Revises: 
Create Date: 2025-10-23 05:34:13.722053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0558e74947c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('students')
    op.drop_table('security_staffs')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('admins')
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('faculties')
    op.drop_table('travels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travels',
    sa.Column('bus_no', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('route', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('route_fee', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('students', mysql.JSON(), nullable=True),
    sa.Column('faculty', mysql.JSON(), nullable=True),
    sa.Column('fee_status', mysql.JSON(), nullable=True),
    sa.Column('boarding_days', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('bus_no'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('faculties',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('subjects', mysql.JSON(), nullable=True),
    sa.Column('classes', mysql.JSON(), nullable=True),
    sa.Column('leisure_periods', mysql.JSON(), nullable=True),
    sa.Column('extra_activities', mysql.JSON(), nullable=True),
    sa.Column('attendance', mysql.JSON(), nullable=True),
    sa.Column('salary_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('approved_by_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('admins',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('security_staffs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('shift', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('working_hours', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salary_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('class_assigned', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mobile', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('fee_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('attendance', mysql.JSON(), nullable=True),
    sa.Column('marks', mysql.JSON(), nullable=True),
    sa.Column('activities', mysql.JSON(), nullable=True),
    sa.Column('portal_access', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
